
import React from 'react';
import { 
  Plane, 
  Train, 
  Utensils, 
  Camera, 
  BedDouble, 
  CheckSquare, 
  Map as MapIcon, 
  List, 
  Settings, 
  Navigation,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  Info,
  Car,
  Sun,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  CloudSun,
  Droplets,
  Home,
  Sparkles,
  QrCode,
  Ticket,
  Stamp,
  Footprints,
  Signpost,
  Star,
  Banknote,
  RefreshCw,
  Clock,
  Plus,
  Minus,
  Edit,
  Route,
  ArrowRight,
  Crosshair,
  MapPin,
  Navigation2,
  TrainFront,
  ArrowLeftRight,
  AlertCircle,
  CreditCard,
  Smartphone,
  AlertTriangle,
  Calculator,
  Users,
  Map,
  ChevronsRight,
  Zap,
  Monitor,
  Maximize,
  Minimize,
  X
} from 'lucide-react';
import { ActivityType } from '../../types';

export const ActivityIcon = ({ type, className }: { type: ActivityType; className?: string }) => {
  switch (type) {
    case ActivityType.FLIGHT: return <Plane className={className} />;
    case ActivityType.TRAIN: return <Train className={className} />;
    case ActivityType.FOOD: return <Utensils className={className} />;
    case ActivityType.SIGHTSEEING: return <Camera className={className} />;
    case ActivityType.HOTEL: return <BedDouble className={className} />;
    case ActivityType.CHECKLIST: return <CheckSquare className={className} />;
    default: return <Info className={className} />;
  }
};

export { 
  MapIcon, 
  List, 
  Settings, 
  Navigation, 
  ChevronDown, 
  ChevronUp, 
  ChevronLeft, 
  ChevronRight, 
  ExternalLink, 
  Car, 
  Plane, 
  BedDouble, 
  Train, 
  Utensils, 
  Camera, 
  CheckSquare, 
  Sun, 
  Cloud, 
  CloudRain, 
  CloudSnow, 
  CloudLightning, 
  CloudFog, 
  CloudSun, 
  Droplets, 
  Home, 
  Sparkles, 
  QrCode, 
  Ticket, 
  Stamp, 
  Footprints, 
  Signpost, 
  Star,
  Banknote,
  RefreshCw, 
  Clock, 
  Plus, 
  Minus,
  Edit,
  Route,
  ArrowRight,
  Crosshair,
  MapPin,
  Navigation2,
  TrainFront,
  ArrowLeftRight,
  AlertCircle,
  CreditCard,
  Smartphone,
  AlertTriangle,
  Info,
  Calculator,
  Users,
  Map,
  ChevronsRight,
  Zap,
  Monitor,
  Maximize,
  Minimize,
  X
};
